export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_PIC_UPLOAD_REQUEST = 'USER_PIC_UPLOAD_REQUEST';
export const USER_PIC_UPLOAD_SUCCESS = 'USER_PIC_UPLOAD_SUCCESS';
export const USER_PIC_UPLOAD_FAIL = 'USER_PIC_UPLOAD_FAIL';

export const GET_PROFILE_DATA_REQUEST = 'GET_PROFILE_DATA_REQUEST';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAIL = 'GET_PROFILE_DATA_FAIL';

export const GET_PROFILE_IMG_REQUEST = 'GET_PROFILE_IMG_REQUEST';
export const GET_PROFILE_IMG_SUCCESS = 'GET_PROFILE_IMG_SUCCESS';
export const GET_PROFILE_IMG_FAIL = 'GET_PROFILE_IMG_FAIL';
